# Generated by Django 5.0.6 on 2026-07-26 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('procurement', '0007_invoice_invoiceitem_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['rfq', 'status'], name='procurement_rfq_id_75714d_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['vendor', 'status'], name='procurement_vendor__e49eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='procurement_due_dat_f89f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['submitted_at'], name='procurement_submitt_b3fb43_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_delivery_date', 'status'], name='procurement_expecte_578387_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['department', 'status'], name='procurement_departm_ab63f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_at'], name='procurement_created_58182d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='procurement_status_ff2f8d_idx'),
        ),
    ]
